---
- name: Refresh provider 
  hosts: localhost
  connection: local
  
  vars:
    - auto_commit: true
    - manageiq_validate_certs: false
      
  roles:
  - syncrou.manageiq-automate
  - syncrou.manageiq-vmdb

  tasks:
    - name: Refresh provider
      manageiq_vmdb:
        href: "href_slug::providers/4"
        action: refresh
      register: refresh_result

    - debug: var=refresh_result
    - debug: var=refresh_result.value.task_id

    - name: Wait for the refresh to end
      manageiq_vmdb:
        href: "href_slug::tasks/{{ refresh_result.value.task_id }}"
      register: task_result
      until: task_result.state == 'Finished' or task_result.status == 'Error'
      failed_when: task_result.status == 'Error'
      retries: 100
      delay: 60

    - debug: var=task_result